### ISSUE TITLE
TypeError: Cannot set property errored of #<Readable> which has only a getter with mail-parser dep.

### ISSUE THREAD

**Issue by gustavos00** [MateMalice/mail-listener2#35] opened 2022-07-18 10:40 UTC
Hello, 
First of all, I don't know if this is the right place to create a issue about my problem.

Basically, when I try to use `.on('mail', (email) => {})` is giving me a error with the mail-parser dependency. The error is: 
`.../node_modules/mailparser/lib/mail-parser.js:141`
`        this.errored = false;`
`TypeError: Cannot set property errored of #<Readable> which has only a getter`

**Comment by MateMalice** [comment] 2023-01-07 05:07
Hi @gustavos00 -

EDIT: I have found that the error only occurred when using NodeJS v 18+; it did not occur in NodeJS v 16. The cause was an old version of a dependency package (mailsplit) that did not appear to be compatible with NodeJS v 18.

I have updated the relevant dependency and will be releasing a fix shortly.

Thank you for pointing this out. :-)

**Comment by MateMalice** [comment] 2023-01-07 06:28
Fixed in [v2.1.1](https://github.com/MateMalice/mail-listener2/releases/tag/v2.1.1).

**Closed as completed by MateMalice** 2023-01-07 06:28 UTC
