### ISSUE TITLE
Can't call to mail-listener from a test case in Cypress

### ISSUE THREAD

**Issue by idanRiski** [MateMalice/mail-listener2#16] opened 2020-03-14 16:10 UTC
I'm trying to code some testing in **cypress** for some ongoing emails and verify their content when they received by your mail-listener
but I've managed to run it and to use his features only inside the *plugin index.js* and it's running before the tests.

When I'm trying to run it through the test case it returns the error below:

      1) An uncaught error was detected outside of a test:
         Uncaught TypeError: Invalid Version: 
    
    This error originated from your test code, not from Cypress.
    
    When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
    
    Cypress could not associate this error to any specific test.
    
    We dynamically generated a new test to display this failure.

Any idea?

**Comment by MateMalice** [comment] 2020-04-01 12:31
Hi idanRiski,

It is difficult to identify the problem without more information. However, the error message seems to indicate that the error occurred in the test code, so it could have something to do with the way you are using Cypress. Unfortunately, I'm not particularly experienced with Cypress (I tend to write my unit tests using Mocha and Chai), so I'd need to dig a little deeper in order to help resolve this.

If you'd like assistance, could you please provide the following:

1. Version(s) of various packages you're using (including Cypress), version of NodeJS, operating system and other relevant environmental info (e.g. are you running in a container, are you connecting to a remote mail server or one run on localhost, etc).
2. An extract of the code you're testing (i.e. the substantive code) - obviously with credentials, secrets and other identifying information redacted.
3. A copy of your Cypress test script that's generating the error.
4. Steps to reproduce.

Since I'm not an expert on Cypress, I can't promise that I'll be able to help, but I am happy to have a look & may be able to assist if the problem is in the way you're using the package itself. :-) 

Cheers,

M

**Comment by Jon-NJ** [comment] 2021-02-15 20:58
I ran into the same problem and I figured out a work-around. The first problem is that the plugin will work in the Node.js engine but not in the browser. Cypress has one context for the browser and this is where the tests execute. If it needs to use a database or some Node.js feature, you have to define a task. The task runs in the Node engine.

Additionally, the require statement still causes the problem you mentioned when it is defined at the top of the module. I have a function that is called from the task and within this function I use the require. The version check problem is not caused by this module but by one of the indirect dependencies. (I forgot which one.) I am also not yet very skilled in Cypress or Node.js but I did manage to get mail-listener2 to work. I don't know yet about 5.

**Comment by Jon-NJ** [comment] 2021-02-15 21:24
I forgot to mention, there was also a problem with package mailparser. A work-around for this was listed here: [https://github.com/jcreigno/nodejs-mail-notifier/issues/43](https://github.com/jcreigno/nodejs-mail-notifier/issues/43). I am a bit confused with all the dependencies and branches. So this may not apply to mail-listener5.

**Comment by alex737876** [comment] 2021-06-12 16:44
Any updates on this? Also would be nice to add a typings file for the mail-listener5 (  .d.ts)

**Comment by Jon-NJ** [comment] 2021-06-12 18:14
Hope this is helpful. I committed my testsuite - [https://github.com/Jon-NJ/bookclub-cypress/blob/main/cypress/plugins/mailmonitor.js](https://github.com/Jon-NJ/bookclub-cypress/blob/main/cypress/plugins/mailmonitor.js). I still have to iron out some of the problems in it. My experience with N/JS and Cypress is limited and I haven't been working on this lately.

**Comment by alex737876** [comment] 2021-06-12 22:57
was working on it until right now... your approach brought me the success! Thank you.
I don't know why it took me so long... there were issues over issues as im not quite familiar with cypress yet. But finally worked!

**Comment by MateMalice** [comment] 2021-06-17 13:14
Thank you for the contributions & comments - the workaround seems to have resolved the issue with Cypress, so I am marking this as closed.

**Closed as completed by MateMalice** 2021-06-17 13:14 UTC
