### ISSUE TITLE
.on("error") gets triggered with every message

### ISSUE THREAD

**Issue by dzg** [MateMalice/mail-listener2#33] opened 2022-02-17 19:41 UTC
For me,  `.on("error")` gets triggered with every message, with `null` for `err`

**Comment by MateMalice** [comment] 2023-01-07 05:06
Hi @dzg -

EDIT: I have done some further digging and found the cause of the problem. It appears that when a file was getting saved, an error was being returned even if the error was "null".

This will be fixed in an upcoming update.

Thank you for pointing this out!

**Comment by MateMalice** [comment] 2023-01-07 06:29
Fixed in [v2.1.1](https://github.com/MateMalice/mail-listener2/releases/tag/v2.1.1).

**Closed as completed by MateMalice** 2023-01-07 06:29 UTC
